apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runboat.fullname" . }}-env
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "runboat.labels" . | nindent 4 }}
type: Opaque
stringData:
  RUNBOAT_API_ADMIN_USER: {{ .Values.config.apiAdminUser | quote }}
  RUNBOAT_API_ADMIN_PASSWD: {{ .Values.config.apiAdminPassword | quote }}
  {{- if .Values.github.token }}
  RUNBOAT_GITHUB_TOKEN: {{ .Values.github.token | quote }}
  {{- end }}
  {{- if .Values.github.webhookSecret }}
  RUNBOAT_GITHUB_WEBHOOK_SECRET: {{ .Values.github.webhookSecret | quote }}
  {{- end }}
  {{- if .Values.gitlab.token }}
  RUNBOAT_GITLAB_TOKEN: {{ .Values.gitlab.token | quote }}
  {{- end }}
  {{- if .Values.gitlab.webhookToken }}
  RUNBOAT_GITLAB_WEBHOOK_TOKEN: {{ .Values.gitlab.webhookToken | quote }}
  {{- end }}
  RUNBOAT_BUILD_SECRET_ENV: {{ include "runboat.buildSecretEnv" . | squote }}
